apiVersion: v1
kind: Secret
metadata:
  name: authserver-admin
type: Opaque
stringData:
  username: "{{ .Values.authserver.admin.username }}"
  password: "{{ .Values.authserver.admin.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: pdp-smcb-keystore
type: Opaque
data:
  keystore: "{{ .Values.authserver.smcb_keystore.keystore | trim }}"
  password: "{{ .Values.authserver.smcb_keystore.password | trim | b64enc }}"
