{{- /* vim: set ft=helm: */ -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeta-guard
  labels:
    app: zeta-guard
  {{- if .Values.authserver.hostname }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | default "letsencrypt-staging" | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName | default "nginx" }}
  {{- if .Values.authserver.hostname }}
  tls:
    - hosts:
        - {{ .Values.authserver.hostname | quote }}
      secretName: "zeta-guard-tls"
  {{- end }}
  rules:
    # do not set host when working with local-cluster
    - {{- if .Values.authserver.hostname }}
      host: {{ .Values.authserver.hostname | quote }}
      {{- end }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  number: 80
          - path: /proxy
            pathType: Prefix
            backend:
              service:
                name: testdriver
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pep-proxy-svc
                port:
                  number: 80
