{{- /* vim: set ft=helm: */ -}}
{{- /* NIC mergeable minion for zeta-guard rules */ -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeta-guard-minion
  labels:
    app.kubernetes.io/name: zeta-guard
    app.kubernetes.io/component: ingress
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/websocket-services: {{ if .Values.routeViaTigerProxy }}"tiger-proxy"{{ else }}"pep-proxy-svc"{{ end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - {{- if .Values.authserver.hostname }}
      host: {{ .Values.authserver.hostname | quote }}
      {{- end }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                {{- if .Values.routeViaTigerProxy }}
                name: tiger-proxy
                port:
                  number: 80
                {{- else }}
                name: authserver
                port:
                  name: http
                {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ if .Values.routeViaTigerProxy }}tiger-proxy{{ else }}pep-proxy-svc{{ end }}
                port:
                  number: 80
