{{- $wif := .Values.opa.workloadIdentityFederation -}}
{{- if and .Values.opa.enabled (and $wif $wif.enabled) .Values.opa.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opa.serviceAccountName | quote }}
  labels:
    app: opa
    component: opa
{{- end }}
