{{- $wif := .Values.opa.workloadIdentityFederation -}}
{{- if and .Values.opa.enabled .Values.opa.bundle.enabled (and $wif $wif.enabled) (and $wif.tokenRenewer $wif.tokenRenewer.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-token-renewer
  labels:
    app: opa
    component: opa
{{- end }}
