{{- $wif := .Values.opa.workloadIdentityFederation -}}
{{- if and .Values.opa.enabled .Values.opa.bundle.enabled (and $wif $wif.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: gematik-oidc-token
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/component: gematik
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
  annotations:
    last-updated: never
type: Opaque
data:
  # Initially empty, CronJob will patch .data.token with base64-encoded OIDC token
  token: ""
{{- end }}
