apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-monitoring-ingress
  labels:
    app.kubernetes.io/name: test-monitoring-ingress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: "{{ .Values.ingressRulesHost }}"
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: frontend-proxy
                port:
                  number: 8080
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: frontend-proxy
                port:
                  number: 8080
