# See https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-demo-0.38.6/charts/opentelemetry-demo/values.yaml
opentelemetry-demo:

  components:

    accounting:
      enabled: false

    ad:
      enabled: false

    cart:
      enabled: false

    checkout:
      enabled: false

    currency:
      enabled: false

    email:
      enabled: false

    fraud-detection:
      enabled: false

    frontend:
      enabled: false

    image-provider:
      enabled: false

    load-generator:
      enabled: false

    payment:
      enabled: false

    product-catalog:
      enabled: false

    quote:
      enabled: false

    recommendation:
      enabled: false

    shipping:
      enabled: false

    flagd:
      enabled: false

    kafka:
      enabled: false

    postgresql:
      enabled: false

    valkey-cart:
      enabled: false

  opentelemetry-collector:
    config:
      processors:
        # this is a workaround for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45428
        resource/delete_k8s_labels:
          attributes:
            - key: app
              action: delete

      service:
        pipelines:
          logs:
            processors:
              - k8sattributes
              - memory_limiter
              - resourcedetection
              - resource
              - resource/delete_k8s_labels
              - batch
          metrics:
            receivers:
              - otlp
              - spanmetrics
          traces:
            receivers:
              - otlp
# ingressRulesHost defines the hostname for all ingress rules in this chart.
ingressRulesHost: "test-monitoring-ingress.localhost"
