apiVersion: apps/v1
kind: Deployment
metadata:
  name: exauthsim
  labels:
    component: exauthsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exauthsim
  template:
    metadata:
      labels:
        app: exauthsim
        component: exauthsim
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name:  "{{ .Values.image.image_pull_secret | default .Values.global.image_pull_secret }}"
      containers:
        - name: exauthsim
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: smcb-keystore
              mountPath: "/app/resources/certificates/C_SMCB_AUT_E256_X509.p12"
              subPath: "smcb-certificates.p12"
              readOnly: true
            - name: tmp
              mountPath: /tmp
          env:
            - name: SMB_KEYSTORE_FILE
              value: "/app/resources/certificates/C_SMCB_AUT_E256_X509.p12"
            - name: SMB_KEYSTORE_ALIAS
              value: "zeta.c_smcb_aut"
            - name: SMB_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-smcb-keystore
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: smcb-keystore
          secret:
            secretName: test-smcb-keystore
            items:
              - key: keystore
                path: "smcb-certificates.p12"
        - name: tmp
          emptyDir: { }
