apiVersion: v1
kind: Service
metadata:
  name: exauthsim
spec:
  selector:
    app: exauthsim
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
  type: ClusterIP
