global:
  image_pull_secret: nil
  registry: europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/
  registry_host: "europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/"

registry_name: ""

# When enabled, injects a changing annotation to force pod rollouts
# on each helm upgrade/apply even if image tag is unchanged.
devMode: false

replicaCount: 1

image:
  tag: latest
  pullPolicy: Always
  repository: tiger-testsuite

env:
  zetaBaseUrl: ""
  zetaProxyUrl: ""
  zetaProxy: "no-proxy"
  tigerEnvironment: cloud
  cucumberTags: "@smoke"
  mvnGoals: "tiger:setup-testenv"
  mvnAdditionalArgs: ""
  serenityExportDir: ""

paths:
  serenityDir: /app/target/site/serenity
  failsafeSummary: /app/target/failsafe-reports/failsafe-summary.xml

workflowUi:
  activateWorkflowUi: false
  trafficVisualization: false
  startBrowser: false
  workflowUiPort: 8080
  workflowUiStartTimeoutInSeconds: 120
  enableTestSelection: false
  runTestsOnStart: true
  autoFetchStatus: true
  autoFetchTimeoutSeconds: 180
  tigerProxyConfiguration:
    adminPort: 9011

service:
  enabled: false
  type: ClusterIP
  annotations: {}
  port: 8080
  nodePort: null

proxyAdminService:
  enabled: false
  type: NodePort
  annotations: {}
  port: null
  nodePort: null
