apiVersion: v1
kind: ConfigMap
metadata:
  name: pep-well-known
  labels:
    app.kubernetes.io/name: pep-proxy
    app.kubernetes.io/component: pep
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
data:
# {{ .Values.authserver.hostname }}
{{- range $path, $file := .Files.Glob "files/well-known/*" }}
  {{ base $path }}: |-
{{ tpl ($file | toString) $ | indent 4 }}
{{- end }}
