{{- if and .Values.opa.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opa.serviceAccountName | quote }}
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/component: pdp
    app.kubernetes.io/version: {{ .Values.opa.image.tag | quote }}
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
{{- end }}
