{{- $wif := .Values.opa.workloadIdentityFederation -}}
{{- if and .Values.opa.enabled .Values.opa.bundle.enabled (and $wif $wif.enabled) (and $wif.tokenRenewer $wif.tokenRenewer.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-token-renewer
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/component: pdp
    app.kubernetes.io/version: {{ .Values.opa.image.tag | quote }}
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
{{- end }}
