{{- if .Values.tokenGenerator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: popp-token-generator
spec:
  selector:
    app: popp-mock
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: popp-statics
spec:
  selector:
    app: popp-mock
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
