apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
  labels:
    app: authserver
    app.kubernetes.io/name: authserver
    app.kubernetes.io/component: pdp
    app.kubernetes.io/version: {{ .Values.authserver.image.tag | quote }}
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
        app.kubernetes.io/name: authserver
        app.kubernetes.io/component: pdp
        {{- include "zeta-guard.baseLabels" . | nindent 8 }}
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: "{{ .Values.authserver.image.image_pull_secret | default .Values.global.image_pull_secret }}"
      {{- with .Values.authserver.hostAlias }}
      hostAliases:
        - ip: {{ .ip | quote }}
          hostnames:
            - {{ .name | quote }}
      {{- end }}
      initContainers:
        - name: keycloak-build
          image: "{{ include "authserver.image" . }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              /opt/keycloak/bin/kc.sh build
              cp -r /opt/keycloak/* /work/
          env:
            - name: SMCB_KEYSTORE_LOCATION
              value: "/opt/keycloak/conf/smcb-certificates.p12"
            - name: SMCB_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pdp-smcb-truststore
                  key: password
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: {{ quote .Values.authServerMetricsEnabled }}
            - name: KC_TRACING_ENABLED
              value: {{ quote .Values.authServerTracingEnabled }}
            - name: KC_DB
              value: "{{ include "authserver.kcDb" . }}"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KC_HTTP_MANAGEMENT_RELATIVE_PATH
              value: "/auth-mgmt"
            # Configure ZETA SMC-B token-exchange provider and OPA toggle
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_ENABLED
              value: "{{ .Values.authserver.provider.smcB.opa.enabled }}"
          volumeMounts:
            - name: keycloak-home
              mountPath: /work
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
      containers:
        - name: keycloak
          image: "{{ include "authserver.image" . }}"
          imagePullPolicy: "{{ .Values.authserver.image.pullPolicy }}"
          args:
            - start
            - --optimized
            - --hostname-strict=false
            - --proxy-headers=xforwarded
            - --hostname={{ .Values.authserver.hostname }}
          livenessProbe:
            httpGet:
              path: /auth-mgmt/health/live/ # align with KC_HTTP_MANAGEMENT_RELATIVE_PATH
              port: http-mgmt-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /auth-mgmt/health/ready/  # align with KC_HTTP_MANAGEMENT_RELATIVE_PATH
              port: http-mgmt-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /auth-mgmt/health/ready/  # align with KC_HTTP_MANAGEMENT_RELATIVE_PATH
              port: http-mgmt-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            # Environment variable 'KEYCLOAK_ADMIN' is deprecated, use 'KC_BOOTSTRAP_ADMIN_USERNAME' instead
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: authserver-admin
                  key: username
            # Environment variable 'KEYCLOAK_ADMIN_PASSWORD' is deprecated, use 'KC_BOOTSTRAP_ADMIN_PASSWORD' instead
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authserver-admin
                  key: password
            - name: SMCB_KEYSTORE_LOCATION
              value: "/opt/keycloak/conf/smcb-certificates.p12"
            - name: SMCB_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pdp-smcb-truststore
                  key: password
            {{- if .Values.devMode }}
            # Enable remote debugging in devMode
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            {{- end }}
            - name: KC_LOG_LEVEL
              value: "{{ .Values.authserver.log.level }}"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_DEBUG
              value: "true"
            - name: KC_DEBUG_PORT
              value: "*:8787"
            - name: JAVA_LOCALE
              value: "-Duser.timezone=Europe/Berlin"
            - name: JAVA_OPTS_APPEND
              value: "-ea"
            - name: KC_LOG_CONSOLE_JSON_FORMAT
              value: "ecs"
            - name: KC_LOG_CONSOLE_OUTPUT
              value: {{ quote .Values.authServerLogConsoleOutput }}
            - name: KC_METRICS_ENABLED
              value: {{ quote .Values.authServerMetricsEnabled }}
            - name: KC_TRACING_ENDPOINT
              value: "http://{{ include "telemetryGateway.hostname" . }}:4317"
            # OPA endpoints and behavior
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_OPA_BASE_URL
              value: "{{ .Values.authserver.provider.smcB.opaBaseUrl }}"
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_DECISION_PATH
              value: "{{ .Values.authserver.provider.smcB.decisionPath }}"
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_CONNECTION_TIMEOUT_MS
              value: "{{ .Values.authserver.provider.smcB.connectionTimeoutMs }}"
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_READ_TIMEOUT_MS
              value: "{{ .Values.authserver.provider.smcB.readTimeoutMs }}"
            - name: KC_SPI_TOKEN_EXCHANGE_PROVIDER_ZETA_SMC_B_TOKEN_EXCHANGE_FAIL_CLOSED
              value: "{{ .Values.authserver.provider.smcB.failClosed }}"
            - name: SMCB_USER_MAX_CLIENTS
              value: "{{ .Values.authserver.config.maxClients }}"
            - name: CLIENT_REGISTRATION_TTL
              value: "{{ .Values.authserver.config.clientRegistrationTTL }}"
            - name: CLIENT_REGISTRATION_SCHEDULER_INTERVAL
              value: "{{ .Values.authserver.config.clientRegistrationSchedulerInterval }}"

            # https://ey-fp-dev.atlassian.net/browse/ZETAP-793
            # TODO: Delete me when client is ready
            - name: CHECK_CLIENT_ATTESTATION_ENABLED
              value: {{ .Values.authserver.config.clientAttestationEnabled | default "false" | quote }}

            # Initial hash for admin events log
            # TODO: should be retrieved from secret
            - name: GENESIS_HASH
              value: 4841c2142fef441daa6ee6c57db65c011935964b14e94a6c8f5ec0447b83526c
              # DB wiring switches by databaseMode value (operator|bitnami)
            {{- if eq .Values.databaseMode "operator" }}
            # Operator-backed DB
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "keycloak.keycloak-db.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "keycloak.keycloak-db.credentials.postgresql.acid.zalan.do"
                  key: password
            - name: KC_DB_SCHEMA
              value: "public"
            {{- else if eq .Values.databaseMode "bitnami" }}
            # DB settings for local (Bitnami)
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/keycloak?sslmode=disable"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql"
                  key: password
            - name: KC_DB_SCHEMA
              value: "public"
            {{- else }}
            # DB settings for external DB
            - name: KC_DB
              value: {{ .Values.authserverDb.kcDb | quote }}
            - name: KC_DB_URL
              value: {{ .Values.authserverDb.kcDbUrl | quote }}
            - name: KC_DB_USERNAME
              value: {{ .Values.authserverDb.kcDbUsername | quote }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authserverDb.kcDbPasswordSecretName | quote }}
                  key: password
            - name: KC_DB_SCHEMA
              value: {{ .Values.authserverDb.kcDbSchema | quote }}
            {{- end }}
          ports:
            - containerPort: 8080 # align with KC_HTTP_PORT
              name: http-port
            - containerPort: 9000 # align with KC_HTTP_MANAGEMENT_PORT
              name: http-mgmt-port
            {{- if .Values.devMode }}
            - containerPort: 5005
              name: jdwp
            {{- end }}
          volumeMounts:
            - name: keycloak-home
              mountPath: /opt/keycloak
            - name: smcb-keystore
              mountPath: "/opt/keycloak/conf/smcb-certificates.p12"
              subPath: "smcb-certificates.p12"
              readOnly: true
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: keycloak-home
          emptyDir: { }
        - name: smcb-keystore
          secret:
            secretName: pdp-smcb-truststore
            items:
              - key: keystore
                path: "smcb-certificates.p12"
        - name: tmp
          emptyDir: { }
